# Default values for NGSA.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
    repository: retaildevcrew
    name: ngsa
    tag: "beta"
ingress:
    hosts:
        - %%INGRESS_PIP%%.nip.io # Replace the IP address with the external IP of the Istio ingress gateway (value of $INGRESS_PIP or run kubectl get svc istio-ingressgateway -n istio-system to see the correct IP)
    paths: 
        - /
