apiVersion: v1
kind: ConfigMap
metadata:
  name: ngsa-config
data:
  LogName: "aksa"
  Region: "West"
  Zone: "AZ-WestUs2"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-admin

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-admin
  namespace: default
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: k8s-admin
 namespace: default
roleRef:
 kind: Role
 name: k8s-admin
 apiGroup: rbac.authorization.k8s.io
subjects: 
  - kind: ServiceAccount
    name: k8s-admin
